# Generated by Django 4.1 on 2024-05-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hotel', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Single', 'Single'), ('Double', 'Double'), ('Deluxe', 'Deluxe')], default='Standard', max_length=20),
        ),
    ]
