# Generated by Django 4.1 on 2024-05-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hotel', '0006_alter_room_room_description_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
