# Generated by Django 4.1 on 2024-05-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hotel', '0007_room_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.CharField(max_length=50),
        ),
    ]
