# Generated by Django 4.1 on 2024-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hotel', '0010_room_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CheckIn', 'CheckIn'), ('CheckOut', 'CheckOut'), ('NotYet', 'NotYet')], default='NotYet', max_length=10),
            preserve_default=False,
        ),
    ]
